# Generated by Django 4.1.1 on 2022-09-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefa",
            options={"verbose_name": "Tarefa", "verbose_name_plural": "Tarefas"},
        ),
        migrations.AddField(
            model_name="tarefa",
            name="complexidade",
            field=models.CharField(
                choices=[
                    ("muito fácil", "Muito fácil"),
                    ("fácil", "Fácil"),
                    ("regular", "Regular"),
                    ("complexo", "Complexo"),
                    ("muito complexo", "Muito complexo"),
                ],
                default=None,
                max_length=25,
                verbose_name="complexidade",
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="data_entrega",
            field=models.DateField(default=None, verbose_name="data_entrega"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("urgente", "Urgente"),
                    ("importante", "Importante"),
                    ("precisa ser feito", "Precisa ser feito"),
                ],
                default="importante",
                max_length=25,
                verbose_name="categoria",
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="criacao",
            field=models.DateField(auto_now_add=True, verbose_name="criacao"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="descricao",
            field=models.CharField(max_length=400, verbose_name="descrição"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluído", "Concluído"),
                    ("pendente", "Pendente"),
                    ("adiado", "Adiado"),
                ],
                default="pendente",
                max_length=25,
                verbose_name="status",
            ),
        ),
        migrations.AlterModelTable(
            name="tarefa",
            table="tarefa",
        ),
    ]
