# Generated by Django 4.1.1 on 2022-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0003_alter_tarefa_complexidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="complexidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muito fácil", "Muito fácil"),
                    ("fácil", "Fácil"),
                    ("regular", "Regular"),
                    ("complexo", "Complexo"),
                    ("muito complexo", "Muito complexo"),
                ],
                default="fácil",
                max_length=25,
                null=True,
                verbose_name="complexidade",
            ),
        ),
    ]
