# Generated by Django 4.1.1 on 2022-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0004_alter_tarefa_complexidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="complexidade",
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_entrega",
            field=models.DateField(
                default=None, null=True, verbose_name="data_entrega"
            ),
        ),
    ]
