# Generated by Django 4.1.1 on 2022-09-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0005_remove_tarefa_complexidade_alter_tarefa_data_entrega"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "email",
                    models.EmailField(max_length=254, null=True, verbose_name="email"),
                ),
                (
                    "telefone",
                    models.CharField(max_length=12, null=True, verbose_name="telefone"),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
                "db_table": "pessoa",
            },
        ),
        migrations.AddField(
            model_name="tarefa",
            name="complexidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muito fácil", "Muito fácil"),
                    ("fácil", "Fácil"),
                    ("regular", "Regular"),
                    ("complexo", "Complexo"),
                    ("muito complexo", "Muito complexo"),
                ],
                max_length=25,
                null=True,
                verbose_name="complexidade",
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="pessoas",
            field=models.ManyToManyField(to="tarefas.pessoa"),
        ),
    ]
